using System.Collections.Generic;
using System.Collections.Immutable;

namespace Elk.Std.Bindings;

/// <summary>
/// Provides access to the standard library functions.
/// The other part of this class is automatically
/// generated by a source code generator.
/// </summary>
public static partial class FunctionBindings
{
    public static bool HasModule(string moduleName)
        => _modules.ContainsKey(moduleName);

    public static StdFunction? GetFunction(string functionName, string? moduleName)
    {
        string fullName = moduleName == null
            ? functionName
            : $"{moduleName}::{functionName}";
        _functions.TryGetValue(fullName, out var result);

        return result;
    }

    public static ImmutableArray<string>? GetModuleFunctionNames(string moduleName)
    {
        _modules.TryGetValue(moduleName, out var functionNames);

        return functionNames;
    }
}