name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
          cache: true
          cache-dependency-path: '*/packages.lock.json'
      - run: |
          dotnet restore --locked-mode
          dotnet build
          dotnet test
